import { v4 as uuidv4 } from "uuid";
import type {
  EndpointDefinition,
  EndpointResult,
  OpenAPISpec,
  ScannerAuth,
  ScanReport,
} from "../types";

/**
 * Exports a test report as an Insomnia v4 export.
 */
export function exportInsomnia(
  report: ScanReport,
  spec: OpenAPISpec,
): Record<string, unknown> {
  const workspaceId = `wrk_${uuidv4().replace(/-/g, "").slice(0, 16)}`;
  const config =
    (spec["x-scanner"] as {
      baseUrl?: string;
      auth?: ScannerAuth;
    } | undefined) || {};
  const baseUrl = config.baseUrl || spec.servers?.[0]?.url || "";

  const resources: Array<Record<string, unknown>> = [
    {
      _id: workspaceId,
      _type: "workspace",
      name: report.meta.specTitle,
      description: `Generated by api-scanner on ${report.meta.timestamp}`,
      scope: "collection",
    },
    buildEnvironment(workspaceId, baseUrl, config),
  ];

  const tagFolders: Record<
    string,
    { id: string; results: EndpointResult[] }
  > = {};
  for (const result of report.results) {
    const tag = result.endpoint.tags?.[0] || "Other";
    if (!tagFolders[tag]) {
      const folderId = `fld_${uuidv4().replace(/-/g, "").slice(0, 16)}`;
      tagFolders[tag] = { id: folderId, results: [] };
      resources.push({
        _id: folderId,
        _type: "request_group",
        parentId: workspaceId,
        name: capitalize(tag),
      });
    }
    tagFolders[tag].results.push(result);
  }

  for (const [, { id: folderId, results }] of Object.entries(tagFolders)) {
    for (const result of results) {
      resources.push(buildInsomniaRequest(result, folderId, baseUrl, config));
    }
  }

  return {
    _type: "export",
    __export_format: 4,
    __export_date: new Date().toISOString(),
    __export_source: "api-scanner",
    resources,
  };
}

function buildInsomniaRequest(
  result: EndpointResult,
  parentId: string,
  baseUrl: string,
  config: { auth?: ScannerAuth },
): Record<string, unknown> {
  const { endpoint } = result;
  const auth = buildInsomniaAuth(config.auth);

  return {
    _id: `req_${uuidv4().replace(/-/g, "").slice(0, 16)}`,
    _type: "request",
    parentId,
    name: endpoint.summary || endpoint.operationId,
    method: endpoint.method,
    url: endpoint.url,
    description: buildDescription(result),
    headers: [
      { name: "Content-Type", value: "application/json" },
      { name: "Accept", value: "application/json" },
    ],
    authentication: auth,
    body: endpoint.requestBody
      ? {
          mimeType: "application/json",
          text: JSON.stringify(endpoint.requestBody, null, 2),
        }
      : {},
    parameters: buildQueryParams({
      parameters: endpoint.parameters || [],
    } as EndpointDefinition),
    metaSortKey: -1,
  };
}

function buildInsomniaAuth(
  auth: ScannerAuth | undefined,
): Record<string, unknown> {
  if (!auth) return { type: "none" };
  if (auth.type === "bearer") {
    return { type: "bearer", token: auth.token || "{{ token }}" };
  }
  if (auth.type === "apikey") {
    return {
      type: "apikey",
      key: auth.header || "X-API-Key",
      value: auth.token || "{{ apiKey }}",
      addTo: "header",
    };
  }
  if (auth.type === "basic") {
    return {
      type: "basic",
      username: auth.username || "",
      password: auth.password || "",
    };
  }
  return { type: "none" };
}

function buildEnvironment(
  workspaceId: string,
  baseUrl: string,
  config: { auth?: ScannerAuth },
): Record<string, unknown> {
  const data: Record<string, string> = { baseUrl };
  if (config.auth?.token) data.token = String(config.auth.token);
  return {
    _id: `env_${uuidv4().replace(/-/g, "").slice(0, 16)}`,
    _type: "environment",
    parentId: workspaceId,
    name: "Base Environment",
    data,
  };
}

function buildQueryParams(endpoint: EndpointDefinition): Array<Record<string, unknown>> {
  return (endpoint.parameters || [])
    .filter((p) => p.in === "query")
    .map((p) => ({
      name: p.name,
      value: String(p.example ?? p.schema?.example ?? ""),
      description: p.description || "",
      disabled: !p.required,
    }));
}

function buildDescription(result: EndpointResult): string {
  const lines: string[] = [];
  lines.push(`**Scan Status**: ${result.status.toUpperCase()}`);
  if (result.response) {
    lines.push(
      `**Last Response**: ${result.response.status} in ${result.response.elapsed}ms`,
    );
  }

  const issues: Array<{ check?: string; type?: string; message: string }> = [
    ...(result.tests || []).filter((t) => t.status === "fail"),
    ...(result.fkIssues || []),
  ];

  if (issues.length > 0) {
    lines.push("\n### Issues Found");
    for (const issue of issues) {
      const label = issue.check || issue.type || "issue";
      lines.push(`- **${label}**: ${issue.message}`);
    }
  }

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
