import { v4 as uuidv4 } from "uuid";
import type { EndpointResult, OpenAPISpec, ScanReport, ScannerAuth } from "../types";

/**
 * Exports a test report as a Postman Collection v2.1.
 */
export function exportPostman(
  report: ScanReport,
  spec: OpenAPISpec,
): Record<string, unknown> {
  const config = (spec["x-scanner"] as { auth?: ScannerAuth } | undefined) || {};
  const auth = config.auth;

  const collection: Record<string, unknown> = {
    info: {
      _postman_id: uuidv4(),
      name: report.meta.specTitle,
      description: `Generated by api-scanner on ${report.meta.timestamp}\n\nEndpoints: ${report.meta.totalEndpoints} | Pass: ${report.meta.passed} | Fail: ${report.meta.failed} | Warn: ${report.meta.warned}`,
      schema:
        "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    auth: buildPostmanAuth(auth),
    variable: buildPostmanVariables(spec),
    item: [],
  };

  const tagGroups: Record<string, EndpointResult[]> = {};
  for (const result of report.results) {
    const tag = result.endpoint.tags?.[0] || "Other";
    if (!tagGroups[tag]) tagGroups[tag] = [];
    tagGroups[tag].push(result);
  }

  const items = collection.item as Array<Record<string, unknown>>;
  for (const [tag, results] of Object.entries(tagGroups)) {
    items.push({
      name: capitalize(tag),
      item: results.map((r) => buildPostmanItem(r, spec)),
    });
  }

  return collection;
}

function buildPostmanItem(
  result: EndpointResult,
  spec: OpenAPISpec,
): Record<string, unknown> {
  const { endpoint } = result;
  const url = buildPostmanUrl(endpoint.url, spec);

  return {
    name: `${endpoint.summary || endpoint.operationId}`,
    _postman_id: uuidv4(),
    request: {
      method: endpoint.method,
      header: [
        { key: "Content-Type", value: "application/json" },
        { key: "Accept", value: "application/json" },
      ],
      url,
      description: buildItemDescription(result),
    },
    response: [],
    event: [
      {
        listen: "test",
        script: {
          type: "text/javascript",
          exec: buildPostmanTestScript(result),
        },
      },
    ],
  };
}

function buildPostmanTestScript(result: EndpointResult): string[] {
  const lines = [
    "// Auto-generated by api-scanner",
    "const jsonData = pm.response.json();",
    "",
  ];

  const expectedStatuses = Object.keys(
    result.endpoint.expectedResponses || {},
  );
  if (expectedStatuses.length > 0) {
    lines.push(`pm.test("Status code is expected", function () {`);
    lines.push(
      `  pm.expect(pm.response.code).to.be.oneOf([${expectedStatuses.join(", ")}]);`,
    );
    lines.push(`});`);
    lines.push("");
  }

  lines.push(`pm.test("Response time is acceptable", function () {`);
  lines.push(`  pm.expect(pm.response.responseTime).to.be.below(2000);`);
  lines.push(`});`);
  lines.push("");

  lines.push(`pm.test("Content-Type is JSON", function () {`);
  lines.push(
    `  pm.expect(pm.response.headers.get("Content-Type")).to.include("application/json");`,
  );
  lines.push(`});`);
  lines.push("");

  if (result.fkIssues?.length) {
    lines.push("// ⚠️ FK Issues detected by api-scanner:");
    for (const issue of result.fkIssues) {
      lines.push(`// [${issue.type}] ${issue.message}`);
    }
    lines.push("");
  }

  const actionable = (result.tests || []).filter(
    (t) =>
      t.status === "fail" &&
      t.check !== "STATUS_CODE" &&
      t.check !== "RESPONSE_TIME",
  );

  for (const t of actionable) {
    lines.push(`// ❌ FAIL: ${t.check} — ${t.message}`);
    const errs = t.details?.errors as string[] | undefined;
    if (errs) {
      for (const e of errs.slice(0, 3)) {
        lines.push(`//   → ${e}`);
      }
    }
  }

  return lines;
}

function buildPostmanUrl(
  rawUrl: string,
  _spec: OpenAPISpec,
): Record<string, unknown> {
  try {
    const u = new URL(rawUrl);
    return {
      raw: rawUrl,
      protocol: u.protocol.replace(":", ""),
      host: u.hostname.split("."),
      port: u.port || undefined,
      path: u.pathname.split("/").filter(Boolean),
    };
  } catch {
    return { raw: rawUrl };
  }
}

function buildPostmanVariables(spec: OpenAPISpec): Array<Record<string, unknown>> {
  const servers = spec.servers || [];
  const baseUrl =
    (spec["x-scanner"] as { baseUrl?: string } | undefined)?.baseUrl ||
    servers[0]?.url ||
    "";
  return [{ key: "baseUrl", value: baseUrl, type: "default" }];
}

function buildPostmanAuth(auth: ScannerAuth | undefined): Record<string, unknown> {
  if (!auth) return { type: "noauth" };
  if (auth.type === "bearer") {
    return {
      type: "bearer",
      bearer: [
        { key: "token", value: auth.token || "{{token}}", type: "string" },
      ],
    };
  }
  if (auth.type === "apikey") {
    return {
      type: "apikey",
      apikey: [
        { key: "key", value: auth.header || "X-API-Key", type: "string" },
        { key: "value", value: auth.token || "{{apiKey}}", type: "string" },
      ],
    };
  }
  return { type: "noauth" };
}

function buildItemDescription(result: EndpointResult): string {
  const lines: string[] = [];
  lines.push(`**Status**: ${result.status.toUpperCase()}`);
  lines.push(
    `**Response**: ${result.response?.status || "?"} (${result.response?.elapsed || "?"}ms)`,
  );

  const fails = (result.tests || []).filter((t) => t.status === "fail");
  const warns = (result.tests || []).filter((t) => t.status === "warn");

  if (fails.length > 0) {
    lines.push("\n**Failures:**");
    for (const f of fails) lines.push(`- ❌ ${f.check}: ${f.message}`);
  }
  if (warns.length > 0) {
    lines.push("\n**Warnings:**");
    for (const w of warns) lines.push(`- ⚠️ ${w.check}: ${w.message}`);
  }
  if (result.fkIssues?.length) {
    lines.push("\n**FK Issues:**");
    for (const fk of result.fkIssues) lines.push(`- 🔗 ${fk.type}: ${fk.message}`);
  }

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
