const { v4: uuidv4 } = require("uuid");

/**
 * Exports a test report as an Insomnia v4 export.
 * Compatible with Insomnia REST client import.
 */
function exportInsomnia(report, spec) {
  const workspaceId = `wrk_${uuidv4().replace(/-/g, "").slice(0, 16)}`;
  const config = spec["x-scanner"] || {};
  const baseUrl = config.baseUrl || spec.servers?.[0]?.url || "";

  const resources = [
    {
      _id: workspaceId,
      _type: "workspace",
      name: report.meta.specTitle,
      description: `Generated by api-scanner on ${report.meta.timestamp}`,
      scope: "collection",
    },
    buildEnvironment(workspaceId, baseUrl, config),
  ];

  // Group by tag → folder
  const tagFolders = {};
  for (const result of report.results) {
    const tag = result.endpoint.tags?.[0] || "Other";
    if (!tagFolders[tag]) {
      const folderId = `fld_${uuidv4().replace(/-/g, "").slice(0, 16)}`;
      tagFolders[tag] = { id: folderId, results: [] };
      resources.push({
        _id: folderId,
        _type: "request_group",
        parentId: workspaceId,
        name: capitalize(tag),
      });
    }
    tagFolders[tag].results.push(result);
  }

  for (const [tag, { id: folderId, results }] of Object.entries(tagFolders)) {
    for (const result of results) {
      resources.push(buildInsomniaRequest(result, folderId, baseUrl, config));
    }
  }

  return {
    _type: "export",
    __export_format: 4,
    __export_date: new Date().toISOString(),
    __export_source: "api-scanner",
    resources,
  };
}

function buildInsomniaRequest(result, parentId, baseUrl, config) {
  const { endpoint } = result;
  const auth = buildInsomniaAuth(config.auth);

  const req = {
    _id: `req_${uuidv4().replace(/-/g, "").slice(0, 16)}`,
    _type: "request",
    parentId,
    name: endpoint.summary || endpoint.operationId,
    method: endpoint.method,
    url: endpoint.url,
    description: buildDescription(result),
    headers: [
      { name: "Content-Type", value: "application/json" },
      { name: "Accept", value: "application/json" },
    ],
    authentication: auth,
    body: endpoint.requestBody
      ? { mimeType: "application/json", text: JSON.stringify(endpoint.requestBody, null, 2) }
      : {},
    parameters: buildQueryParams(endpoint),
    metaSortKey: -1,
  };

  return req;
}

function buildInsomniaAuth(auth) {
  if (!auth) return { type: "none" };
  if (auth.type === "bearer") {
    return { type: "bearer", token: auth.token || "{{ token }}" };
  }
  if (auth.type === "apikey") {
    return {
      type: "apikey",
      key: auth.header || "X-API-Key",
      value: auth.token || "{{ apiKey }}",
      addTo: "header",
    };
  }
  if (auth.type === "basic") {
    return { type: "basic", username: auth.username || "", password: auth.password || "" };
  }
  return { type: "none" };
}

function buildEnvironment(workspaceId, baseUrl, config) {
  const data = { baseUrl };
  if (config.auth?.token) data.token = config.auth.token;
  return {
    _id: `env_${uuidv4().replace(/-/g, "").slice(0, 16)}`,
    _type: "environment",
    parentId: workspaceId,
    name: "Base Environment",
    data,
  };
}

function buildQueryParams(endpoint) {
  return (endpoint.parameters || [])
    .filter((p) => p.in === "query")
    .map((p) => ({
      name: p.name,
      value: String(p.example ?? p.schema?.example ?? ""),
      description: p.description || "",
      disabled: !p.required,
    }));
}

function buildDescription(result) {
  const lines = [];
  lines.push(`**Scan Status**: ${result.status.toUpperCase()}`);
  if (result.response) {
    lines.push(`**Last Response**: ${result.response.status} in ${result.response.elapsed}ms`);
  }

  const issues = [
    ...(result.tests || []).filter((t) => t.status === "fail"),
    ...(result.fkIssues || []),
  ];

  if (issues.length > 0) {
    lines.push("\n### Issues Found");
    for (const issue of issues) {
      const label = issue.check || issue.type;
      lines.push(`- **${label}**: ${issue.message}`);
    }
  }

  return lines.join("\n");
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = { exportInsomnia };
