const { v4: uuidv4 } = require("uuid");

/**
 * Exports a test report as a Postman Collection v2.1.
 * The collection includes pre-request scripts and test assertions
 * matching the issues found during scanning.
 */
function exportPostman(report, spec) {
  const config = spec["x-scanner"] || {};
  const auth = config.auth;

  const collection = {
    info: {
      _postman_id: uuidv4(),
      name: report.meta.specTitle,
      description: `Generated by api-scanner on ${report.meta.timestamp}\n\nEndpoints: ${report.meta.totalEndpoints} | Pass: ${report.meta.passed} | Fail: ${report.meta.failed} | Warn: ${report.meta.warned}`,
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    auth: buildPostmanAuth(auth),
    variable: buildPostmanVariables(spec),
    item: [],
  };

  // Group items by tag
  const tagGroups = {};
  for (const result of report.results) {
    const tag = result.endpoint.tags?.[0] || "Other";
    if (!tagGroups[tag]) tagGroups[tag] = [];
    tagGroups[tag].push(result);
  }

  for (const [tag, results] of Object.entries(tagGroups)) {
    const folder = {
      name: capitalize(tag),
      item: results.map((r) => buildPostmanItem(r, spec)),
    };
    collection.item.push(folder);
  }

  return collection;
}

function buildPostmanItem(result, spec) {
  const { endpoint } = result;
  const url = buildPostmanUrl(endpoint.url, spec);

  const item = {
    name: `${endpoint.summary || endpoint.operationId}`,
    _postman_id: uuidv4(),
    request: {
      method: endpoint.method,
      header: [
        { key: "Content-Type", value: "application/json" },
        { key: "Accept", value: "application/json" },
      ],
      url,
      description: buildItemDescription(result),
    },
    response: [],
    event: [
      {
        listen: "test",
        script: {
          type: "text/javascript",
          exec: buildPostmanTestScript(result),
        },
      },
    ],
  };

  return item;
}

function buildPostmanTestScript(result) {
  const lines = [
    "// Auto-generated by api-scanner",
    "const jsonData = pm.response.json();",
    "",
  ];

  // Status code test
  const expectedStatuses = Object.keys(result.endpoint?.expectedResponses || {});
  if (expectedStatuses.length > 0) {
    lines.push(`pm.test("Status code is expected", function () {`);
    lines.push(`  pm.expect(pm.response.code).to.be.oneOf([${expectedStatuses.join(", ")}]);`);
    lines.push(`});`);
    lines.push("");
  }

  // Response time test
  lines.push(`pm.test("Response time is acceptable", function () {`);
  lines.push(`  pm.expect(pm.response.responseTime).to.be.below(2000);`);
  lines.push(`});`);
  lines.push("");

  // Content type
  lines.push(`pm.test("Content-Type is JSON", function () {`);
  lines.push(`  pm.expect(pm.response.headers.get("Content-Type")).to.include("application/json");`);
  lines.push(`});`);
  lines.push("");

  // FK issue comments
  if (result.fkIssues?.length > 0) {
    lines.push("// ⚠️ FK Issues detected by api-scanner:");
    for (const issue of result.fkIssues) {
      lines.push(`// [${issue.type}] ${issue.message}`);
    }
    lines.push("");
  }

  // Tests from scan results that failed or warned
  const actionable = (result.tests || []).filter(
    (t) => t.status === "fail" && t.check !== "STATUS_CODE" && t.check !== "RESPONSE_TIME"
  );

  for (const t of actionable) {
    lines.push(`// ❌ FAIL: ${t.check} — ${t.message}`);
    if (t.details?.errors) {
      for (const e of t.details.errors.slice(0, 3)) {
        lines.push(`//   → ${e}`);
      }
    }
  }

  return lines;
}

function buildPostmanUrl(rawUrl, spec) {
  // Split into parts for Postman's URL model
  try {
    const u = new URL(rawUrl);
    return {
      raw: rawUrl,
      protocol: u.protocol.replace(":", ""),
      host: u.hostname.split("."),
      port: u.port || undefined,
      path: u.pathname.split("/").filter(Boolean),
    };
  } catch {
    return { raw: rawUrl };
  }
}

function buildPostmanVariables(spec) {
  const servers = spec.servers || [];
  const baseUrl = spec["x-scanner"]?.baseUrl || servers[0]?.url || "";
  return [{ key: "baseUrl", value: baseUrl, type: "default" }];
}

function buildPostmanAuth(auth) {
  if (!auth) return { type: "noauth" };
  if (auth.type === "bearer") {
    return {
      type: "bearer",
      bearer: [{ key: "token", value: auth.token || "{{token}}", type: "string" }],
    };
  }
  if (auth.type === "apikey") {
    return {
      type: "apikey",
      apikey: [
        { key: "key", value: auth.header || "X-API-Key", type: "string" },
        { key: "value", value: auth.token || "{{apiKey}}", type: "string" },
      ],
    };
  }
  return { type: "noauth" };
}

function buildItemDescription(result) {
  const lines = [];
  lines.push(`**Status**: ${result.status.toUpperCase()}`);
  lines.push(`**Response**: ${result.response?.status || "?"} (${result.response?.elapsed || "?"}ms)`);

  const fails = (result.tests || []).filter((t) => t.status === "fail");
  const warns = (result.tests || []).filter((t) => t.status === "warn");

  if (fails.length > 0) {
    lines.push("\n**Failures:**");
    for (const f of fails) lines.push(`- ❌ ${f.check}: ${f.message}`);
  }
  if (warns.length > 0) {
    lines.push("\n**Warnings:**");
    for (const w of warns) lines.push(`- ⚠️ ${w.check}: ${w.message}`);
  }
  if (result.fkIssues?.length > 0) {
    lines.push("\n**FK Issues:**");
    for (const fk of result.fkIssues) lines.push(`- 🔗 ${fk.type}: ${fk.message}`);
  }

  return lines.join("\n");
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

module.exports = { exportPostman };
